### ISSUE TITLE
[Navigation] Display and filter streaming where the media is available

### ISSUE THREAD

**Issue by GabrielleBarbosa** [Miller-GS/MC426A-TV-Application#14]
## Parent Epic
- #13 

## Description
As a user I would like to know which streaming service has the media I am looking for, so that it is easy for me to watch what I am interested in.

## Acceptance Criteria
- [ ] The streaming service should be returned in the GET response
- [ ] The user's location should be considered to retrieve what streaming service has the media
- [ ] The streaming service should be a searching filter 

## Notes
- How will we get the user's country? (ip, request field, database)
 
## Fibonacci Estimative
| Expected         | Real     |
|--------------|-----------|
| 3 |       |

**Comment by Vinschers** [comment]
Deprioritized
