### ISSUE TITLE
[Navigation] Display the order of franchises

### ISSUE THREAD

**Issue by GabrielleBarbosa** [Miller-GS/MC426A-TV-Application#15]
## Parent Epic
- #13 

## Description
As a user I would like to know the airing order of movie or tv shows in their franchises, so that I can know what media to watch next.

## Acceptance Criteria
- [ ] The franchise of the media (if it exists) should be returned in the GET response
- [ ] The list of the media in the franchise should be in order of aired date
- [ ] There should be a new route to retrieve more detailed information about a media franchise
 
## Fibonacci Estimative
| Expected         | Real     |
|--------------|-----------|
| 5 |       |

**Comment by Vinschers** [comment]
Deprioritized
